#!/usr/bin/env bash

set -euo pipefail

echo "~~~ :docker: building container"
docker build -t build_info_generator .

echo "~~~ :docker: running build_info_generator"
docker run \
  -e BUILDKITE_BUILD_NUMBER \
  -e BUILDKITE_PIPELINE_SLUG \
  -e BUILDKITE_PLUGIN_BUILD_INFO_BUILD_GROUP \
  -e BUILDKITE_PLUGIN_BUILD_INFO_OUTPUT_FILE \
  --rm \
  -it \
  -v $(pwd):/workspace \
  build_info_generator